version: '3.8'

services: 
    mysqldb:
        image: mysql:5.7
        restart: unless-stopped
        env_file:
          - .env
        environment:
          - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
          - MYSQL_DATABASE=$MYSQLDB_DATABASE
        ports:
          - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
        volumes:
          - db:/var/lib/mysql
    jetmon:
        build: .
        env_file:
          - .env
        volumes:
          - .:/jetmon
          # Don't sync the node_modules directory back to the client.
          - "/jetmon/node_modules"
        environment:
          - DB_HOST=mysqldb
          - DB_USER=$MYSQLDB_USER
          - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
          - DB_NAME=$MYSQLDB_DATABASE
          - DB_PORT=$MYSQLDB_DOCKER_PORT

volumes: 
  db:
