package api

import (
	"net/http"

	"github.com/Automattic/jetmon/internal/apikeys"
)

type serverHandler func(*Server, http.ResponseWriter, *http.Request)

func (h serverHandler) bind(s *Server) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		h(s, w, r)
	}
}

type routeDef struct {
	Method         string
	Path           string
	OperationID    string
	Summary        string
	Tags           []string
	Scope          apikeys.Scope
	SuccessStatus  int
	RequestSchema  string
	ResponseSchema string
	JSONBody       bool
	BodyRequired   bool
	Idempotency    bool
	Handler        serverHandler
}

func (r routeDef) pattern() string {
	return r.Method + " " + r.Path
}

func (r routeDef) authenticated() bool {
	return r.Scope != ""
}

func (r routeDef) register(s *Server, mux *http.ServeMux) {
	handler := r.Handler.bind(s)
	if r.Idempotency {
		handler = s.withIdempotency(handler)
	}
	if r.JSONBody {
		handler = s.withJSONBodyLimit(handler)
	}
	if r.authenticated() {
		handler = s.requireScope(r.Scope, handler)
	}
	mux.HandleFunc(r.pattern(), handler)
}

func apiRoutes() []routeDef {
	return []routeDef{
		{
			Method:         http.MethodGet,
			Path:           "/api/v1/health",
			OperationID:    "getHealth",
			Summary:        "Check API and database health",
			Tags:           []string{"Utility"},
			SuccessStatus:  http.StatusOK,
			ResponseSchema: "HealthResponse",
			Handler:        (*Server).handleHealth,
		},
		{
			Method:         http.MethodGet,
			Path:           "/api/v1/ready",
			OperationID:    "getReady",
			Summary:        "Check whether the host is ready to take traffic",
			Tags:           []string{"Utility"},
			SuccessStatus:  http.StatusOK,
			ResponseSchema: "ReadyResponse",
			Handler:        (*Server).handleReady,
		},
		{
			Method:         http.MethodGet,
			Path:           "/api/v1/openapi.json",
			OperationID:    "getOpenAPI",
			Summary:        "Return the OpenAPI 3.1 route contract",
			Tags:           []string{"Utility"},
			Scope:          scopeRead,
			SuccessStatus:  http.StatusOK,
			ResponseSchema: "OpenAPIDocument",
			Handler:        (*Server).handleOpenAPIJSON,
		},
		{
			Method:         http.MethodGet,
			Path:           "/api/v1/monitor/stats",
			OperationID:    "getMonitorStats",
			Summary:        "Return the latest Monitor stats snapshot",
			Tags:           []string{"Utility"},
			Scope:          scopeRead,
			SuccessStatus:  http.StatusOK,
			ResponseSchema: "MonitorStatsResponse",
			Handler:        (*Server).handleMonitorStats,
		},
		{
			Method:         http.MethodGet,
			Path:           "/api/v1/monitor/drain-status",
			OperationID:    "getMonitorDrainStatus",
			Summary:        "Return in-flight work counters for shutdown drain monitoring",
			Tags:           []string{"Utility"},
			Scope:          scopeRead,
			SuccessStatus:  http.StatusOK,
			ResponseSchema: "DrainStatusResponse",
			Handler:        (*Server).handleMonitorDrainStatus,
		},
		{
			Method:         http.MethodGet,
			Path:           "/api/v1/verifliers/quorum-report",
			OperationID:    "getVerifliersQuorumReport",
			Summary:        "Return per-vantage Veriflier health for quorum diagnostics",
			Tags:           []string{"Utility"},
			Scope:          scopeRead,
			SuccessStatus:  http.StatusOK,
			ResponseSchema: "QuorumReportResponse",
			Handler:        (*Server).handleVerifliersQuorumReport,
		},
		{
			Method:         http.MethodGet,
			Path:           "/api/v1/audit-log",
			OperationID:    "listAuditLog",
			Summary:        "Query the operational audit trail with filtering and pagination",
			Tags:           []string{"Utility"},
			Scope:          scopeRead,
			SuccessStatus:  http.StatusOK,
			ResponseSchema: "AuditLogListEnvelope",
			Handler:        (*Server).handleListAuditLog,
		},
		{
			Method:         http.MethodGet,
			Path:           "/api/v1/monitor/db-config",
			OperationID:    "getMonitorDBConfigStatus",
			Summary:        "Return sanitized DB config reload status",
			Tags:           []string{"Utility"},
			Scope:          scopeRead,
			SuccessStatus:  http.StatusOK,
			ResponseSchema: "DBConfigStatusResponse",
			Handler:        (*Server).handleMonitorDBConfigStatus,
		},
		{
			Method:         http.MethodGet,
			Path:           "/api/v1/me",
			OperationID:    "getCurrentAPIKey",
			Summary:        "Return the authenticated API key identity",
			Tags:           []string{"Identity"},
			Scope:          scopeRead,
			SuccessStatus:  http.StatusOK,
			ResponseSchema: "MeResponse",
			Handler:        (*Server).handleMe,
		},
		{
			Method:         http.MethodGet,
			Path:           "/api/v1/rollout/capabilities",
			OperationID:    "getRolloutCapabilities",
			Summary:        "Return API-driven rollout capabilities",
			Tags:           []string{"Rollout"},
			Scope:          scopeRead,
			SuccessStatus:  http.StatusOK,
			ResponseSchema: "RolloutCapabilitiesResponse",
			Handler:        (*Server).handleRolloutCapabilities,
		},
		{
			Method:         http.MethodPost,
			Path:           "/api/v1/rollout/sessions",
			OperationID:    "createRolloutSession",
			Summary:        "Create an API-driven rollout session",
			Tags:           []string{"Rollout"},
			Scope:          scopeAdmin,
			SuccessStatus:  http.StatusCreated,
			RequestSchema:  "RolloutSessionRequest",
			ResponseSchema: "RolloutSessionResponse",
			JSONBody:       true,
			BodyRequired:   true,
			Idempotency:    true,
			Handler:        (*Server).handleCreateRolloutSession,
		},
		{
			Method:         http.MethodGet,
			Path:           "/api/v1/rollout/jobs/{job_id}",
			OperationID:    "getRolloutJob",
			Summary:        "Get rollout job status",
			Tags:           []string{"Rollout"},
			Scope:          scopeRead,
			SuccessStatus:  http.StatusOK,
			ResponseSchema: "RolloutJobResponse",
			Handler:        (*Server).handleGetRolloutJob,
		},
		{
			Method:         http.MethodPost,
			Path:           "/api/v1/rollout/preflight",
			OperationID:    "runRolloutPreflight",
			Summary:        "Run API-driven rollout preflight",
			Tags:           []string{"Rollout"},
			Scope:          scopeAdmin,
			SuccessStatus:  http.StatusOK,
			RequestSchema:  "RolloutRangeRequest",
			ResponseSchema: "RolloutOperationResponse",
			JSONBody:       true,
			BodyRequired:   true,
			Idempotency:    true,
			Handler:        (*Server).handleRolloutPreflight,
		},
		{
			Method:         http.MethodPost,
			Path:           "/api/v1/rollout/smoke",
			OperationID:    "runRolloutSmoke",
			Summary:        "Run read-only rollout smoke checks",
			Tags:           []string{"Rollout"},
			Scope:          scopeAdmin,
			SuccessStatus:  http.StatusOK,
			RequestSchema:  "RolloutRangeRequest",
			ResponseSchema: "RolloutOperationResponse",
			JSONBody:       true,
			BodyRequired:   true,
			Idempotency:    true,
			Handler:        (*Server).handleRolloutSmoke,
		},
		{
			Method:         http.MethodPost,
			Path:           "/api/v1/rollout/seed",
			OperationID:    "seedRolloutSideState",
			Summary:        "Plan or execute rollout side-state seed/adoption",
			Tags:           []string{"Rollout"},
			Scope:          scopeAdmin,
			SuccessStatus:  http.StatusOK,
			RequestSchema:  "RolloutRangeRequest",
			ResponseSchema: "RolloutOperationResponse",
			JSONBody:       true,
			BodyRequired:   true,
			Idempotency:    true,
			Handler:        (*Server).handleRolloutSeed,
		},
		{
			Method:         http.MethodPost,
			Path:           "/api/v1/rollout/final-reconcile",
			OperationID:    "finalRolloutReconcile",
			Summary:        "Run final side-state reconcile after v1 stops",
			Tags:           []string{"Rollout"},
			Scope:          scopeAdmin,
			SuccessStatus:  http.StatusOK,
			RequestSchema:  "RolloutRangeRequest",
			ResponseSchema: "RolloutOperationResponse",
			JSONBody:       true,
			BodyRequired:   true,
			Idempotency:    true,
			Handler:        (*Server).handleRolloutFinalReconcile,
		},
		{
			Method:         http.MethodPost,
			Path:           "/api/v1/rollout/activate-buckets",
			OperationID:    "activateRolloutBuckets",
			Summary:        "Activate an API-controlled v2 bucket range",
			Tags:           []string{"Rollout"},
			Scope:          scopeAdmin,
			SuccessStatus:  http.StatusOK,
			RequestSchema:  "RolloutRangeRequest",
			ResponseSchema: "RolloutOperationResponse",
			JSONBody:       true,
			BodyRequired:   true,
			Idempotency:    true,
			Handler:        (*Server).handleRolloutActivateBuckets,
		},
		{
			Method:         http.MethodPost,
			Path:           "/api/v1/rollout/release-buckets",
			OperationID:    "releaseRolloutBuckets",
			Summary:        "Release an API-controlled v2 bucket range",
			Tags:           []string{"Rollout"},
			Scope:          scopeAdmin,
			SuccessStatus:  http.StatusOK,
			RequestSchema:  "RolloutRangeRequest",
			ResponseSchema: "RolloutOperationResponse",
			JSONBody:       true,
			BodyRequired:   true,
			Idempotency:    true,
			Handler:        (*Server).handleRolloutReleaseBuckets,
		},
		{
			Method:         http.MethodGet,
			Path:           "/api/v1/rollout/status",
			OperationID:    "getRolloutStatus",
			Summary:        "Return API-driven rollout status",
			Tags:           []string{"Rollout"},
			Scope:          scopeRead,
			SuccessStatus:  http.StatusOK,
			ResponseSchema: "RolloutStatusResponse",
			Handler:        (*Server).handleRolloutStatus,
		},
		{
			Method:         http.MethodGet,
			Path:           "/api/v1/rollout/bucket-coverage",
			OperationID:    "getRolloutBucketCoverage",
			Summary:        "Check rollout bucket coverage",
			Tags:           []string{"Rollout"},
			Scope:          scopeRead,
			SuccessStatus:  http.StatusOK,
			ResponseSchema: "RolloutGateResponse",
			Handler:        (*Server).handleRolloutBucketCoverage,
		},
		{
			Method:         http.MethodGet,
			Path:           "/api/v1/rollout/activity-check",
			OperationID:    "getRolloutActivityCheck",
			Summary:        "Check recent rollout activity",
			Tags:           []string{"Rollout"},
			Scope:          scopeRead,
			SuccessStatus:  http.StatusOK,
			ResponseSchema: "RolloutGateResponse",
			Handler:        (*Server).handleRolloutActivityCheck,
		},
		{
			Method:         http.MethodGet,
			Path:           "/api/v1/rollout/projection-drift",
			OperationID:    "getRolloutProjectionDrift",
			Summary:        "Check legacy projection drift",
			Tags:           []string{"Rollout"},
			Scope:          scopeRead,
			SuccessStatus:  http.StatusOK,
			ResponseSchema: "RolloutGateResponse",
			Handler:        (*Server).handleRolloutProjectionDrift,
		},
		{
			Method:         http.MethodPost,
			Path:           "/api/v1/rollout/compare-methods",
			OperationID:    "compareRolloutMethods",
			Summary:        "Run non-authoritative rollout method comparison",
			Tags:           []string{"Rollout"},
			Scope:          scopeAdmin,
			SuccessStatus:  http.StatusOK,
			RequestSchema:  "RolloutRangeRequest",
			ResponseSchema: "RolloutOperationResponse",
			JSONBody:       true,
			BodyRequired:   true,
			Idempotency:    true,
			Handler:        (*Server).handleRolloutCompareMethods,
		},
		{
			Method:         http.MethodPost,
			Path:           "/api/v1/rollout/stage-policy",
			OperationID:    "stageRolloutPolicy",
			Summary:        "Plan or execute staged rollout check-policy migration",
			Tags:           []string{"Rollout"},
			Scope:          scopeAdmin,
			SuccessStatus:  http.StatusOK,
			RequestSchema:  "RolloutRangeRequest",
			ResponseSchema: "RolloutOperationResponse",
			JSONBody:       true,
			BodyRequired:   true,
			Idempotency:    true,
			Handler:        (*Server).handleRolloutStagePolicy,
		},
		{
			Method:         http.MethodGet,
			Path:           "/api/v1/sites",
			OperationID:    "listSites",
			Summary:        "List monitored sites",
			Tags:           []string{"Sites"},
			Scope:          scopeRead,
			SuccessStatus:  http.StatusOK,
			ResponseSchema: "SiteListEnvelope",
			Handler:        (*Server).handleListSites,
		},
		{
			Method:         http.MethodGet,
			Path:           "/api/v1/sites/{id}",
			OperationID:    "getSite",
			Summary:        "Get one monitored site",
			Tags:           []string{"Sites"},
			Scope:          scopeRead,
			SuccessStatus:  http.StatusOK,
			ResponseSchema: "SiteDetail",
			Handler:        (*Server).handleGetSite,
		},
		{
			Method:         http.MethodPost,
			Path:           "/api/v1/sites",
			OperationID:    "createSite",
			Summary:        "Create a monitored site",
			Tags:           []string{"Sites"},
			Scope:          scopeWrite,
			SuccessStatus:  http.StatusCreated,
			RequestSchema:  "CreateSiteRequest",
			ResponseSchema: "Site",
			JSONBody:       true,
			BodyRequired:   true,
			Idempotency:    true,
			Handler:        (*Server).handleCreateSite,
		},
		{
			Method:         http.MethodPatch,
			Path:           "/api/v1/sites/{id}",
			OperationID:    "updateSite",
			Summary:        "Update a monitored site",
			Tags:           []string{"Sites"},
			Scope:          scopeWrite,
			SuccessStatus:  http.StatusOK,
			RequestSchema:  "UpdateSiteRequest",
			ResponseSchema: "Site",
			JSONBody:       true,
			BodyRequired:   true,
			Handler:        (*Server).handleUpdateSite,
		},
		{
			Method:        http.MethodDelete,
			Path:          "/api/v1/sites/{id}",
			OperationID:   "deleteSite",
			Summary:       "Soft-delete a monitored site",
			Tags:          []string{"Sites"},
			Scope:         scopeWrite,
			SuccessStatus: http.StatusNoContent,
			Handler:       (*Server).handleDeleteSite,
		},
		{
			Method:         http.MethodPost,
			Path:           "/api/v1/sites/{id}/pause",
			OperationID:    "pauseSite",
			Summary:        "Pause monitoring for a site",
			Tags:           []string{"Sites"},
			Scope:          scopeWrite,
			SuccessStatus:  http.StatusOK,
			ResponseSchema: "Site",
			Idempotency:    true,
			Handler:        (*Server).handlePauseSite,
		},
		{
			Method:         http.MethodPost,
			Path:           "/api/v1/sites/{id}/resume",
			OperationID:    "resumeSite",
			Summary:        "Resume monitoring for a site",
			Tags:           []string{"Sites"},
			Scope:          scopeWrite,
			SuccessStatus:  http.StatusOK,
			ResponseSchema: "Site",
			Idempotency:    true,
			Handler:        (*Server).handleResumeSite,
		},
		{
			Method:         http.MethodPost,
			Path:           "/api/v1/sites/{id}/trigger-now",
			OperationID:    "triggerSiteCheck",
			Summary:        "Run an immediate site check",
			Tags:           []string{"Sites"},
			Scope:          scopeWrite,
			SuccessStatus:  http.StatusOK,
			ResponseSchema: "TriggerNowResponse",
			Idempotency:    true,
			Handler:        (*Server).handleTriggerNow,
		},
		{
			Method:         http.MethodGet,
			Path:           "/api/v1/sites/{id}/events",
			OperationID:    "listSiteEvents",
			Summary:        "List events for a site",
			Tags:           []string{"Events"},
			Scope:          scopeRead,
			SuccessStatus:  http.StatusOK,
			ResponseSchema: "EventListEnvelope",
			Handler:        (*Server).handleListSiteEvents,
		},
		{
			Method:         http.MethodGet,
			Path:           "/api/v1/sites/{id}/events/{event_id}",
			OperationID:    "getSiteEvent",
			Summary:        "Get a site-scoped event",
			Tags:           []string{"Events"},
			Scope:          scopeRead,
			SuccessStatus:  http.StatusOK,
			ResponseSchema: "EventDetail",
			Handler:        (*Server).handleGetEventBySite,
		},
		{
			Method:         http.MethodGet,
			Path:           "/api/v1/sites/{id}/events/{event_id}/transitions",
			OperationID:    "listEventTransitions",
			Summary:        "List transitions for a site event",
			Tags:           []string{"Events"},
			Scope:          scopeRead,
			SuccessStatus:  http.StatusOK,
			ResponseSchema: "TransitionListEnvelope",
			Handler:        (*Server).handleListTransitions,
		},
		{
			Method:         http.MethodGet,
			Path:           "/api/v1/events/{event_id}",
			OperationID:    "getEvent",
			Summary:        "Get an event by ID",
			Tags:           []string{"Events"},
			Scope:          scopeRead,
			SuccessStatus:  http.StatusOK,
			ResponseSchema: "EventDetail",
			Handler:        (*Server).handleGetEvent,
		},
		{
			Method:         http.MethodPost,
			Path:           "/api/v1/sites/{id}/events/{event_id}/close",
			OperationID:    "closeEvent",
			Summary:        "Manually close a site event",
			Tags:           []string{"Events"},
			Scope:          scopeWrite,
			SuccessStatus:  http.StatusOK,
			RequestSchema:  "CloseEventRequest",
			ResponseSchema: "EventDetail",
			JSONBody:       true,
			Idempotency:    true,
			Handler:        (*Server).handleCloseEvent,
		},
		{
			Method:         http.MethodGet,
			Path:           "/api/v1/sites/{id}/uptime",
			OperationID:    "getSiteUptime",
			Summary:        "Get site uptime statistics",
			Tags:           []string{"Statistics"},
			Scope:          scopeRead,
			SuccessStatus:  http.StatusOK,
			ResponseSchema: "UptimeResponse",
			Handler:        (*Server).handleSiteUptime,
		},
		{
			Method:         http.MethodGet,
			Path:           "/api/v1/sites/{id}/response-time",
			OperationID:    "getSiteResponseTime",
			Summary:        "Get site response-time statistics",
			Tags:           []string{"Statistics"},
			Scope:          scopeRead,
			SuccessStatus:  http.StatusOK,
			ResponseSchema: "ResponseTimeResponse",
			Handler:        (*Server).handleSiteResponseTime,
		},
		{
			Method:         http.MethodGet,
			Path:           "/api/v1/sites/{id}/timing-breakdown",
			OperationID:    "getSiteTimingBreakdown",
			Summary:        "Get site timing breakdown statistics",
			Tags:           []string{"Statistics"},
			Scope:          scopeRead,
			SuccessStatus:  http.StatusOK,
			ResponseSchema: "TimingBreakdownResponse",
			Handler:        (*Server).handleSiteTimingBreakdown,
		},
		{
			Method:         http.MethodGet,
			Path:           "/api/v1/webhooks",
			OperationID:    "listWebhooks",
			Summary:        "List webhooks",
			Tags:           []string{"Webhooks"},
			Scope:          scopeRead,
			SuccessStatus:  http.StatusOK,
			ResponseSchema: "WebhookListEnvelope",
			Handler:        (*Server).handleListWebhooks,
		},
		{
			Method:         http.MethodGet,
			Path:           "/api/v1/webhooks/{id}",
			OperationID:    "getWebhook",
			Summary:        "Get one webhook",
			Tags:           []string{"Webhooks"},
			Scope:          scopeRead,
			SuccessStatus:  http.StatusOK,
			ResponseSchema: "Webhook",
			Handler:        (*Server).handleGetWebhook,
		},
		{
			Method:         http.MethodPost,
			Path:           "/api/v1/webhooks",
			OperationID:    "createWebhook",
			Summary:        "Create a webhook",
			Tags:           []string{"Webhooks"},
			Scope:          scopeWrite,
			SuccessStatus:  http.StatusCreated,
			RequestSchema:  "CreateWebhookRequest",
			ResponseSchema: "WebhookWithSecret",
			JSONBody:       true,
			BodyRequired:   true,
			Idempotency:    true,
			Handler:        (*Server).handleCreateWebhook,
		},
		{
			Method:         http.MethodPatch,
			Path:           "/api/v1/webhooks/{id}",
			OperationID:    "updateWebhook",
			Summary:        "Update a webhook",
			Tags:           []string{"Webhooks"},
			Scope:          scopeWrite,
			SuccessStatus:  http.StatusOK,
			RequestSchema:  "UpdateWebhookRequest",
			ResponseSchema: "Webhook",
			JSONBody:       true,
			BodyRequired:   true,
			Handler:        (*Server).handleUpdateWebhook,
		},
		{
			Method:        http.MethodDelete,
			Path:          "/api/v1/webhooks/{id}",
			OperationID:   "deleteWebhook",
			Summary:       "Delete a webhook",
			Tags:          []string{"Webhooks"},
			Scope:         scopeWrite,
			SuccessStatus: http.StatusNoContent,
			Handler:       (*Server).handleDeleteWebhook,
		},
		{
			Method:         http.MethodPost,
			Path:           "/api/v1/webhooks/{id}/rotate-secret",
			OperationID:    "rotateWebhookSecret",
			Summary:        "Rotate a webhook signing secret",
			Tags:           []string{"Webhooks"},
			Scope:          scopeWrite,
			SuccessStatus:  http.StatusOK,
			ResponseSchema: "WebhookWithSecret",
			Idempotency:    true,
			Handler:        (*Server).handleRotateWebhookSecret,
		},
		{
			Method:         http.MethodGet,
			Path:           "/api/v1/webhooks/{id}/deliveries",
			OperationID:    "listWebhookDeliveries",
			Summary:        "List webhook deliveries",
			Tags:           []string{"Webhook deliveries"},
			Scope:          scopeRead,
			SuccessStatus:  http.StatusOK,
			ResponseSchema: "WebhookDeliveryListEnvelope",
			Handler:        (*Server).handleListDeliveries,
		},
		{
			Method:         http.MethodPost,
			Path:           "/api/v1/webhooks/{id}/deliveries/{delivery_id}/retry",
			OperationID:    "retryWebhookDelivery",
			Summary:        "Retry an abandoned webhook delivery",
			Tags:           []string{"Webhook deliveries"},
			Scope:          scopeWrite,
			SuccessStatus:  http.StatusOK,
			ResponseSchema: "WebhookDelivery",
			Idempotency:    true,
			Handler:        (*Server).handleRetryDelivery,
		},
		{
			Method:         http.MethodGet,
			Path:           "/api/v1/alert-contacts",
			OperationID:    "listAlertContacts",
			Summary:        "List alert contacts",
			Tags:           []string{"Alert contacts"},
			Scope:          scopeRead,
			SuccessStatus:  http.StatusOK,
			ResponseSchema: "AlertContactListEnvelope",
			Handler:        (*Server).handleListAlertContacts,
		},
		{
			Method:         http.MethodGet,
			Path:           "/api/v1/alert-contacts/{id}",
			OperationID:    "getAlertContact",
			Summary:        "Get one alert contact",
			Tags:           []string{"Alert contacts"},
			Scope:          scopeRead,
			SuccessStatus:  http.StatusOK,
			ResponseSchema: "AlertContact",
			Handler:        (*Server).handleGetAlertContact,
		},
		{
			Method:         http.MethodPost,
			Path:           "/api/v1/alert-contacts",
			OperationID:    "createAlertContact",
			Summary:        "Create an alert contact",
			Tags:           []string{"Alert contacts"},
			Scope:          scopeWrite,
			SuccessStatus:  http.StatusCreated,
			RequestSchema:  "CreateAlertContactRequest",
			ResponseSchema: "AlertContact",
			JSONBody:       true,
			BodyRequired:   true,
			Idempotency:    true,
			Handler:        (*Server).handleCreateAlertContact,
		},
		{
			Method:         http.MethodPatch,
			Path:           "/api/v1/alert-contacts/{id}",
			OperationID:    "updateAlertContact",
			Summary:        "Update an alert contact",
			Tags:           []string{"Alert contacts"},
			Scope:          scopeWrite,
			SuccessStatus:  http.StatusOK,
			RequestSchema:  "UpdateAlertContactRequest",
			ResponseSchema: "AlertContact",
			JSONBody:       true,
			BodyRequired:   true,
			Handler:        (*Server).handleUpdateAlertContact,
		},
		{
			Method:        http.MethodDelete,
			Path:          "/api/v1/alert-contacts/{id}",
			OperationID:   "deleteAlertContact",
			Summary:       "Delete an alert contact",
			Tags:          []string{"Alert contacts"},
			Scope:         scopeWrite,
			SuccessStatus: http.StatusNoContent,
			Handler:       (*Server).handleDeleteAlertContact,
		},
		{
			Method:         http.MethodPost,
			Path:           "/api/v1/alert-contacts/{id}/test",
			OperationID:    "testAlertContact",
			Summary:        "Send a test alert through a contact",
			Tags:           []string{"Alert contacts"},
			Scope:          scopeWrite,
			SuccessStatus:  http.StatusOK,
			ResponseSchema: "AlertContactTestResponse",
			Idempotency:    true,
			Handler:        (*Server).handleAlertContactTest,
		},
		{
			Method:         http.MethodGet,
			Path:           "/api/v1/alert-contacts/{id}/deliveries",
			OperationID:    "listAlertContactDeliveries",
			Summary:        "List alert-contact deliveries",
			Tags:           []string{"Alert deliveries"},
			Scope:          scopeRead,
			SuccessStatus:  http.StatusOK,
			ResponseSchema: "AlertDeliveryListEnvelope",
			Handler:        (*Server).handleListAlertDeliveries,
		},
		{
			Method:         http.MethodPost,
			Path:           "/api/v1/alert-contacts/{id}/deliveries/{delivery_id}/retry",
			OperationID:    "retryAlertContactDelivery",
			Summary:        "Retry an abandoned alert-contact delivery",
			Tags:           []string{"Alert deliveries"},
			Scope:          scopeWrite,
			SuccessStatus:  http.StatusOK,
			ResponseSchema: "AlertDelivery",
			Idempotency:    true,
			Handler:        (*Server).handleRetryAlertDelivery,
		},
	}
}
