version: '3.8'

services:
    mysqldb:
        image: mysql:5.7
        restart: unless-stopped
        env_file:
          - .env
        environment:
          - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
          - MYSQL_DATABASE=$MYSQLDB_DATABASE
        ports:
          - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
        volumes:
          - db:/var/lib/mysql
    jetmon:
        hostname: docker.jetmon.dev.com
        build:
          context: ../
          dockerfile: docker/Dockerfile_jetmon
        env_file:
          - .env
        volumes:
          - ../:/jetmon
          # Don't sync the node_modules directory back to the client.
          - "/jetmon/node_modules"
        environment:
          - DB_HOST=mysqldb
          - DB_USER=$MYSQLDB_USER
          - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
          - DB_NAME=$MYSQLDB_DATABASE
          - DB_PORT=$MYSQLDB_DOCKER_PORT
          - VERIFLIER_AUTH_TOKEN=$VERIFLIER_AUTH_TOKEN
          - VERIFLIER_PORT=$VERIFLIER_DOCKER_PORT
          - WPCOM_JETMON_AUTH_TOKEN=$WPCOM_JETMON_AUTH_TOKEN
        ports:
          - $JETMON_LOCAL_PORT:$JETMON_DOCKER_PORT
          - $JETMON_STATUS_LOCAL_PORT:$JETMON_STATUS_DOCKER_PORT
        depends_on:
          - mysqldb
    veriflier:
        build:
          context: ../
          dockerfile: docker/Dockerfile_veriflier
        volumes:
          - ../:/opt
        ports:
          - $VERIFLIER_LOCAL_PORT:$VERIFLIER_DOCKER_PORT
        environment:
          - VERIFLIER_AUTH_TOKEN=$VERIFLIER_AUTH_TOKEN
          - VERIFLIER_PORT=$VERIFLIER_DOCKER_PORT
          - JETMON_PORT=$JETMON_DOCKER_PORT
    php-apache:
        image: php:apache
        hostname: test.local
        volumes:
          - ./php-apache/html:/var/www/html
        command: >
          bash -c "a2enmod rewrite
          && apache2-foreground"

volumes:
  db:
