FROM golang:1.22 AS builder

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o jetmon-testsite ./cmd/jetmon-testsite/

FROM scratch

COPY --from=builder /src/jetmon-testsite /jetmon-testsite

EXPOSE 8091/tcp 8443/tcp

ENTRYPOINT ["/jetmon-testsite"]
